# Generated by Django 3.0.1 on 2019-12-28 00:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191228_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 12, 28, 0, 22, 49, 17225, tzinfo=utc), verbose_name='Date Posted'),
            preserve_default=False,
        ),
    ]
