# Generated by Django 3.0.1 on 2020-01-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200104_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=50000, verbose_name='Blog Body'),
        ),
    ]
